--자체조인

SELECT E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
    FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO;

-- E1과 E2는 EMP 테이블을 다른 별칭으로 사용하여 구분합니다.
-- EMPNO는 직원 번호, ENAME은 직원 이름, MGR은 상사의 직원 번호를 나타냅니다.

SELECT E1.EMPNO, E1.ENAME, E1.MGR, E2.EMPNO AS MGR_EMPNO, E2.ENAME AS MGR_ENAME

-- FROM EMP E1, EMP E2 구절은 쿼리에서 사용하는 테이블을 지정합니다.
-- "EMP" 테이블을 E1과 E2라는 서로 다른 별칭으로 사용하고 이를 자체 조인하는 것으로 보입니다.

FROM EMP E1, EMP E2

-- WHERE E1.MGR = E2.EMPNO는 두 개의 EMP 테이블 인스턴스를 연결하는 조건입니다.
-- 이 조건은 E1의 "MGR" 열이 E2의 "EMPNO" 열과 일치하는 경우를 찾아

WHERE E1.MGR = E2.EMPNO;

--외부조인(왼)
SELECT E.ENAME, E.DEPTNO, DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO(+)
ORDER BY E.DEPTNO;

SELECT E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
        FROM EMP E1, EMP E2
    WHERE E1.MGR = E2.EMPNO(+)

--외부조인(오)
SELECT E.ENAME, E.DEPTNO, D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO(+) = D.DEPTNO
ORDER BY E.DEPTNO

SELECT E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR(+) = E2.EMPNO
ORDER BY E1.EMPNO;

--조인 연습문제
--1. 급여가 2000초과인 사원들의 부서정보, 사원정보
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E NATURAL JOIN DEPT D
WHERE E.SAL > 2000;

--2. 부서별 평균급여, 최대급여, 사원수
SELECT DEPTNO, ROUND(AVG(SAL),2) AS AVG_SAL, MAX(SAL),MIN(SAL),COUNT(*) AS CNT
FROM EMP E JOIN DEPT D USING (DEPTNO)
GROUP BY DEPTNO, D.DNAME;

--3. 부서정보 사원정보를 부서번호 사원이름순 정렬
SELECT E.DEPTNO, DNAME, EMPNO, ENAME, JOB, SAL
  FROM EMP E RIGHT OUTER JOIN DEPT D 
  ON E.DEPTNO = D.DEPTNO
ORDER BY E.DEPTNO, ENAME;

